In [1]:
!pip install torch

In [2]:
import torch

In [3]:
torch.zeros([3, 4])

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [4]:
torch.ones([3, 4, 3])

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

In [6]:
x = torch.Tensor([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

In [7]:
x.size()

torch.Size([3, 4])

In [8]:
x.shape

torch.Size([3, 4])

In [9]:
x[0]

tensor([1., 2., 3., 4.])

In [10]:
x[0, 0]

tensor(1.)

In [11]:
x[:, 0]

tensor([1., 5., 9.])

In [12]:
x + 10

tensor([[11., 12., 13., 14.],
        [15., 16., 17., 18.],
        [19., 20., 21., 22.]])

In [13]:
x ** 2

tensor([[  1.,   4.,   9.,  16.],
        [ 25.,  36.,  49.,  64.],
        [ 81., 100., 121., 144.]])

In [14]:
y = torch.Tensor([[12, 11, 10, 9],
                  [8, 7, 6, 5],
                  [4, 3, 2, 1]])

In [15]:
x + y

tensor([[13., 13., 13., 13.],
        [13., 13., 13., 13.],
        [13., 13., 13., 13.]])

In [16]:
x * y

tensor([[12., 22., 30., 36.],
        [40., 42., 42., 40.],
        [36., 30., 22., 12.]])

In [17]:
x / y

tensor([[ 0.0833,  0.1818,  0.3000,  0.4444],
        [ 0.6250,  0.8571,  1.1667,  1.6000],
        [ 2.2500,  3.3333,  5.5000, 12.0000]])

In [18]:
x % y

tensor([[1., 2., 3., 4.],
        [5., 6., 1., 3.],
        [1., 1., 1., 0.]])

In [19]:
torch.exp(x)

tensor([[2.7183e+00, 7.3891e+00, 2.0086e+01, 5.4598e+01],
        [1.4841e+02, 4.0343e+02, 1.0966e+03, 2.9810e+03],
        [8.1031e+03, 2.2026e+04, 5.9874e+04, 1.6275e+05]])

In [22]:
torch.log(x)

tensor([[0.0000, 0.6931, 1.0986, 1.3863],
        [1.6094, 1.7918, 1.9459, 2.0794],
        [2.1972, 2.3026, 2.3979, 2.4849]])

In [23]:
torch.sin(x)

tensor([[ 0.8415,  0.9093,  0.1411, -0.7568],
        [-0.9589, -0.2794,  0.6570,  0.9894],
        [ 0.4121, -0.5440, -1.0000, -0.5366]])

In [25]:
x > 3

tensor([[False, False, False,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])

In [26]:
mask = x > 3

In [27]:
x[mask]

tensor([ 4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [28]:
x[x > 3]

tensor([ 4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [29]:
y = x

In [30]:
y[0, 0] = 999

In [31]:
x

tensor([[999.,   2.,   3.,   4.],
        [  5.,   6.,   7.,   8.],
        [  9.,  10.,  11.,  12.]])

In [32]:
y

tensor([[999.,   2.,   3.,   4.],
        [  5.,   6.,   7.,   8.],
        [  9.,  10.,  11.,  12.]])

In [33]:
x = torch.Tensor([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

In [34]:
y = x.clone()

In [35]:
y[0, 0] = 999
print(x)
print(y)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])
tensor([[999.,   2.,   3.,   4.],
        [  5.,   6.,   7.,   8.],
        [  9.,  10.,  11.,  12.]])


In [36]:
x.dtype

torch.float32

In [37]:
x = x.double()

In [38]:
x

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]], dtype=torch.float64)

In [39]:
import numpy as np

In [40]:
x = np.array([[1, 2, 3, 4],
              [4, 3, 2, 1]])

In [41]:
x = torch.from_numpy(x)

In [42]:
x

tensor([[1, 2, 3, 4],
        [4, 3, 2, 1]])

In [43]:
x = x.numpy()
x

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

In [16]:
x = torch.rand([2000, 3000])

In [4]:
torch.cuda.is_available()

True

In [5]:
torch.device('cuda:0')

device(type='cuda', index=0)

In [7]:
torch.device('cpu')

device(type='cpu')

In [9]:
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')

In [17]:
x_cude = x.to(device)

In [18]:
x_cude

tensor([[0.6591, 0.7548, 0.3538,  ..., 0.8897, 0.8758, 0.3167],
        [0.5448, 0.7093, 0.5100,  ..., 0.9218, 0.8133, 0.3066],
        [0.4097, 0.9161, 0.6221,  ..., 0.3046, 0.5710, 0.0789],
        ...,
        [0.6013, 0.3091, 0.2431,  ..., 0.1294, 0.1125, 0.4952],
        [0.3930, 0.4122, 0.0635,  ..., 0.0328, 0.0086, 0.8906],
        [0.4031, 0.5096, 0.9454,  ..., 0.7186, 0.7859, 0.1941]],
       device='cuda:0')

In [19]:
%time y = (x - x + x * 10.0) ** 2

CPU times: user 16.9 ms, sys: 40.8 ms, total: 57.7 ms
Wall time: 68.8 ms


In [20]:
%time y_cude = (x_cude - x_cude + x_cude * 10.0) ** 2

CPU times: user 1 µs, sys: 1 ms, total: 1.01 ms
Wall time: 1.01 ms
