In [1]:
import torch

In [2]:
x = torch.tensor([[1., 2., 3., 4.],
                  [5., 6., 7., 8.],
                  [9., 10., 11., 12.]], requires_grad=True)

In [3]:
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')

In [4]:
x = x.to(device)

In [5]:
function = 10 * (x ** 2).sum()

In [6]:
function.backward()

In [7]:
print(x.grad, '< - gradient')

tensor([[ 20.,  40.,  60.,  80.],
        [100., 120., 140., 160.],
        [180., 200., 220., 240.]]) < - gradient


In [8]:
# 2.7

w = torch.tensor([[5., 10.],
                  [1., 2.]], requires_grad=True)

In [12]:
func = torch.log(torch.log(w + 7)).prod()

In [13]:
func.backward()

In [14]:
print(w.grad, '<- gradient')

tensor([[0.0201, 0.0109],
        [0.0449, 0.0351]]) <- gradient


In [16]:
w = torch.tensor([[5., 10.], [1., 2.]], requires_grad=True)
alpha = 0.001

for _ in range(500):
    # critical: calculate the function inside the loop
    function = (w + 7).log().log().prod()
    function.backward()
    w.data -=  alpha * w.grad
    w.grad.zero_()

print(w)

tensor([[4.9900, 9.9948],
        [0.9775, 1.9825]], requires_grad=True)


In [18]:
w = torch.tensor([[5., 10.], [1., 2.]], requires_grad=True)
optimizer = torch.optim.SGD([w], lr=0.001)

for _ in range(500):
    # critical: calculate the function inside the loop
    function = (w + 7).log().log().prod()
    function.backward()
    optimizer.step()
    optimizer.zero_grad()

print(w)

tensor([[4.9900, 9.9948],
        [0.9775, 1.9825]], requires_grad=True)
